Added Navigation branch component
yatinko/eazyshop pull request #10
Opened 2022-10-13 07:08 UTC by yatinko

Screenshot of the Navigation bar.
![image](https://user-images.githubusercontent.com/32841505/195525669-1d90d2c7-6f32-47ec-b344-9314ab9e8bec.png)

Screenshot of the navigation drawer when hovered on a nav link.
![image](https://user-images.githubusercontent.com/32841505/195525858-8a92b71c-5824-418b-87ee-4ab48812ebe4.png)

2022-10-14 06:22 UTC, vijay9967 commented
Ok

On Thu, 13 Oct 2022, 12:38 pm yatinko, ***@***.***> wrote:

> @yatinko <https://github.com/yatinko> requested your review on: #10
> <https://github.com/yatinko/eazyshop/pull/10> Added Navigation branch
> component.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/yatinko/eazyshop/pull/10#event-7578108701>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALLA7UDYX4QQRCDVBIME3NLWC6YO5ANCNFSM6AAAAAARD6WKJU>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-10-15 16:10 UTC, Aman22225 requested changes
Please add home Button to Nav Bar.

2022-10-16 05:13 UTC, itzashish14 reviewed
After adding home in nav bar and specializing the logo u can merge

2022-10-16 09:33 UTC, yatinko commented
Added the home link to the navbar. It is also dynamic as it has an active state when user is in homepage

When user is in homepage
![image](https://user-images.githubusercontent.com/32841505/196028384-1ed3e6f1-e970-448f-a9fe-8314965275c7.png)

When user is in another page
![image](https://user-images.githubusercontent.com/32841505/196028397-a86c18ea-6b44-4ca2-b654-d6a78fbbb08a.png)

2022-10-20 15:16 UTC, Aman22225 approved these changes
Well done.

2022-10-20 16:04 UTC, merged